### ISSUE TITLE
Fails in Hyper 1.3.1

### ISSUE THREAD

**Issue by coreyog** [Nonsense331/hyper-dance-party#2]
![image](https://cloud.githubusercontent.com/assets/2836207/24265052/d9b4a732-0fc7-11e7-9bd7-e593fc2a7618.png)

Restarting hyper after installing the plugin through hpm causes hyper to fail. The cursor sits in the upper left hand corner and never prints the prompt. No interactivity. The above error shows up in the Developer Tools.

**Comment by Nonsense331** [comment]
1.0.4 should work with the new hyper.
