### ISSUE TITLE
Example config in README.md is out of date

### ISSUE THREAD

**Issue by coreyog** [Nonsense331/hyper-dance-party#3]
It seems that .hyper.js has changed it's structure and I can't put objects in the `plugins` property. As a result nothing changes with the plugin installed.

Putting an object into the plugins array causes hyper to break when starting up.

**Comment by Nonsense331** [comment]
The plugins: {} hash goes under config in .hyper.js not in the plugins array. The string 'hyper-dance-party' is what needs to go in the plugins array. It is a bit confusing they are named the same.

**Comment by coreyog** [comment]
You're right that is confusing. It is exactly what your example shows but I missed it. Sorry about that.
